version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: blank-imports

formatters:
  enable:
    - gofmt
    - goimports
