front-matter: true

rules:
  line-length:
    max: 80
    exclude:
      - code-blocks
      - tables
      - urls
  heading-style:
    style: atx
  heading-increment: true
  first-line-heading:
    level: 1
  no-duplicate-headings: true
  no-trailing-spaces: true
  no-hard-tabs: true
  no-multiple-blanks:
    max: 1
  single-trailing-newline: true
  fenced-code-style:
    style: backtick
  fenced-code-language: true
  no-bare-urls: true
  blank-line-around-headings: true
  blank-line-around-lists: true
  blank-line-around-fenced-code: true
  list-indent:
    spaces: 2
  max-file-length:
    max: 300
  no-trailing-punctuation-in-heading: true
  no-emphasis-as-heading: true
  paragraph-readability:
    max-grade: 14.0
    min-words: 20
  paragraph-structure:
    max-sentences: 6
    max-words: 40
  catalog: true
  required-structure: true
  front-matter-validation: true
  include: true

overrides:
  - files: ["README.md"]
    rules:
      paragraph-structure:
        max-sentences: 30
  - files: ["rules/MDS002-heading-style/good/setext.md",
            "internal/rules/MDS002-heading-style/good/setext.md"]
    rules:
      heading-style:
        style: setext
  - files: ["rules/MDS010-fenced-code-style/good/tilde.md",
            "internal/rules/MDS010-fenced-code-style/good/tilde.md"]
    rules:
      fenced-code-style:
        style: tilde
  - files: ["rules/MDS016-list-indent/good/spaces-4.md",
            "internal/rules/MDS016-list-indent/good/spaces-4.md"]
    rules:
      list-indent:
        spaces: 4
  - files: ["rules/MDS*/README.md", "internal/rules/MDS*/README.md"]
    rules:
      required-structure:
        template: rules/proto.md
      front-matter-validation:
        required:
          - id
          - name
          - description
        fields:
          id: string
          name: string
          description: string
  - files: ["plan/[0-9]*.md"]
    rules:
      required-structure:
        template: plan/proto.md
      front-matter-validation:
        required:
          - id
          - title
          - status
        fields:
          id: int
          title: string
          status:
            type: string
            enum:
              - 🔲
              - ✅
  - files: ["guides/*.md"]
    rules:
      line-length:
        max: 600
        exclude:
          - code-blocks
          - tables
          - urls
      max-file-length:
        max: 600
      paragraph-readability:
        max-grade: 24.0
        min-words: 20
      paragraph-structure:
        max-sentences: 12
        max-words: 120

ignore:
  - "rules/*/bad/**"
  - "rules/*/bad.md"
  - "rules/*/good/**"
  - "rules/*/fixed/**"
  - "internal/rules/*/bad/**"
  - "internal/rules/*/bad.md"
  - "internal/rules/*/good/**"
  - "internal/rules/*/fixed/**"
