front-matter: true

rules:
  line-length:
    max: 80
    exclude:
      - code-blocks
      - tables
      - urls
  heading-style:
    style: atx
  heading-increment: true
  first-line-heading:
    level: 1
  empty-section-body:
    min-level: 2
    max-level: 6
    allow-marker: allow-empty-section
  no-duplicate-headings: true
  no-trailing-spaces: true
  no-hard-tabs: true
  no-multiple-blanks:
    max: 1
  single-trailing-newline: true
  fenced-code-style:
    style: backtick
  fenced-code-language: true
  no-bare-urls: true
  blank-line-around-headings: true
  blank-line-around-lists: true
  blank-line-around-fenced-code: true
  list-indent:
    spaces: 2
  max-file-length:
    max: 300
  table-format:
    pad: 1
  table-readability:
    max-column-width-variance: 60
    max-columns: 8
    max-rows: 30
    max-words-per-cell: 30
  cross-file-reference-integrity:
    include: []
    exclude:
      # Placeholder link in internal/rules/proto.md; not a real repo path.
      - "../../../archetypes/NAME"
    strict: true
  token-budget:
    max: 8000
    mode: heuristic
    ratio: 0.75
    tokenizer: builtin
    encoding: cl100k_base
  no-trailing-punctuation-in-heading: true
  no-emphasis-as-heading: true
  paragraph-readability:
    max-grade: 14.0
    min-words: 20
  paragraph-structure:
    max-sentences: 6
    max-words: 40
  # Experimental rule: keep disabled until classifier-backed scoring is ready.
  conciseness-scoring: false
  catalog: true
  required-structure: true
  include: true

overrides:
  - files: ["README.md"]
    rules:
      paragraph-structure:
        max-sentences: 30
  - files: ["PLAN.md"]
    rules:
      table-readability:
        max-rows: 80
  - files: ["internal/rules/MDS002-heading-style/good/setext.md"]
    rules:
      heading-style:
        style: setext
  - files: ["internal/rules/MDS010-fenced-code-style/good/tilde.md"]
    rules:
      fenced-code-style:
        style: tilde
  - files: ["internal/rules/MDS016-list-indent/good/spaces-4.md"]
    rules:
      list-indent:
        spaces: 4
  - files: ["internal/rules/MDS*/README.md"]
    rules:
      required-structure:
        template: internal/rules/proto.md
  - files: ["plan/*.md"]
    rules:
      required-structure:
        template: plan/proto.md
  - files: ["guides/*.md"]
    rules:
      line-length:
        max: 600
        exclude:
          - code-blocks
          - tables
          - urls
      max-file-length:
        max: 600
      token-budget:
        max: 12000
        mode: heuristic
        ratio: 0.75
        tokenizer: builtin
        encoding: cl100k_base
      paragraph-readability:
        max-grade: 24.0
        min-words: 20
      paragraph-structure:
        max-sentences: 12
        max-words: 120

ignore:
  - "internal/rules/*/bad/**"
  - "internal/rules/*/bad.md"
  - "internal/rules/*/good/**"
  - "internal/rules/*/fixed/**"
