package integration

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/jeduden/mdsmith/internal/config"
	"github.com/jeduden/mdsmith/internal/fix"
	"github.com/jeduden/mdsmith/internal/rule"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestFix_MDS048_RegeneratesAndStagesGitattributes drives the real
// fix.Fixer end-to-end on a repo whose .gitattributes is out of sync.
// It covers the interaction between the engine's two Check calls
// (once before fix passes, once inside applyFixPasses) and asserts
// that Fix actually runs, .gitattributes is regenerated, and the
// regenerated file lands in the index. A direct r.Fix unit test
// would not catch a regression where Check suppresses repeats and
// keeps Fix from being invoked.
func TestFix_MDS048_RegeneratesAndStagesGitattributes(t *testing.T) {
	dir := t.TempDir()
	require.NoError(t, exec.Command("git", "init", dir).Run())
	require.NoError(t, exec.Command(
		"git", "-C", dir, "config", "core.hooksPath",
		filepath.Join(dir, ".git", "hooks"),
	).Run())
	require.NoError(t, exec.Command(
		"git", "-C", dir, "config", "--local",
		"merge.mdsmith.driver", "mdsmith merge-driver run %O %A %B %P",
	).Run())

	mdFile := filepath.Join(dir, "test.md")
	mdContent := "# Test\n\n<?catalog glob=\"*.md\"?>\n<?/catalog?>\n"
	require.NoError(t, os.WriteFile(mdFile, []byte(mdContent), 0o644))

	attrPath := filepath.Join(dir, ".gitattributes")
	initial := "# BEGIN mdsmith merge-driver\nold.md merge=mdsmith\n# END mdsmith merge-driver\n"
	require.NoError(t, os.WriteFile(attrPath, []byte(initial), 0o644))

	cfg := &config.Config{
		Rules: map[string]config.RuleCfg{
			"git-hook-sync": {Enabled: true},
		},
	}

	fixer := &fix.Fixer{
		Config: cfg,
		Rules:  rule.All(),
	}

	result := fixer.Fix([]string{mdFile})
	require.Empty(t, result.Errors, "unexpected errors: %v", result.Errors)

	updated, err := os.ReadFile(attrPath)
	require.NoError(t, err)
	expected := "# BEGIN mdsmith merge-driver\n" +
		"*.md merge=mdsmith\n" +
		"*.markdown merge=mdsmith\n" +
		"# END mdsmith merge-driver\n"
	assert.Equal(t, expected, string(updated),
		".gitattributes must be regenerated by the real Fixer pipeline")

	staged, err := exec.Command(
		"git", "-C", dir, "ls-files", "--stage", "--", ".gitattributes",
	).Output()
	require.NoError(t, err)
	assert.Contains(t, string(staged), ".gitattributes",
		"Fixer pipeline must stage the regenerated .gitattributes")
}
